homepage:
    pattern:  /semdrops/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:index }

getCategories:
    pattern: /semdrops/get_categories/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:getCategories }

showCategories:
    pattern: /semdrops/show_categories/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:showCategories }

addCategory:
    pattern: /semdrops/add_category
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:addCategory }

addCategoryphp:
    pattern: /add_categoryphp
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:addCategoryphp }


